### PR TITLE
N subset of Z type theorem added.

### PR DESCRIPTION
**Pull request by mikekab**
Added several Integer Theorems coinciding with property declarations.
Removed use of the two argument minus from the workspace.

### CODE REVIEW

**Comment by mikekab** [comment]
Just merged latest changes on Clemson master so that this can be automatically merged.

**Comment by yushan87** [comment]
So you are introducing more operations into Integer_Template. This is something that we will need to discuss with Murali. In my opinion, those shouldn't be primary operations, because we gain no performance by adding that operation and we can definitely get the same results by using "<=" operation. Also, the realization will have to change or else it will fail when building a jar.

**Comment by mikekab** [comment]
Those new ops can be removed.  However, if you use those instead of numbers
in your program, you can avoid having numbers using the built in Z.

**Comment by yushan87** [comment]
Well, we need to solve the problem at its source and get rid of the built-in Z. Other instances of the problem might come up if we don't solve it!

**Comment by mikekab** [comment]
I added a little method in the prover package that looks for numeric
symbols and types them as naturals.  So things will prove without those
Integer_Template changes until we get rid of that built-in Z.  How do I get
rid of those pre-existing commits in my pull request?

**Comment by yushan87** [comment]
You shouldn't need that method. I am trying (or trying to get someone else) to get rid of the built-in Z. Once we do that, the VC Generator and Prover should work without having to change anything.

I don't think you can. Once you do "git pull" that sort of merges your changes with those you brought in. That is why we don't use "git pull" and use "git rebase" instead.

**Comment by mikekab** [comment]
We might as well just leave the program numbers as they are until they can
be handled externally by the Character standard concept.  As far as I know,
only the program numbers are currently using the built-in Z.

**Comment by yushan87** [comment]
Ok, I think I may have fixed the problem with program numbers using the built in Z. We probably just need the type theorem relating N and Z. 

Why did you change all the subtraction to addition of the negative value? Do we not have theorems involving subtraction?

**Comment by mikekab** [comment]
Can't have both in the same theory file. Just adding a the type theorem
will allow you to gen VC's, but there are some notable omissions in the
last version like assoc & commut of addition.

**Pull request merged**
